spring.application.name=BetterReads
server.servlet.context-path=/

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ider-database.westeurope.cloudapp.azure.com/h678288
spring.datasource.username=h678288
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=trace
